apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-ui
        env:
        - name: DISABLE_GKE_METADATA
          value: "true"
        - name: ARGO_ARCHIVE_LOGS
          value: "true"