apiVersion: v1
kind: Service
metadata:
  name: kubeflow-webhook
  namespace: kubeflow-user-example-com
spec:
  selector:
    app: kubeflow-webhook
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP